# Generated by Django 4.0.8 on 2022-10-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('comments', models.CharField(max_length=100)),
                ('reciept', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'expenses',
                'managed': True,
            },
        ),
    ]
