# Generated by Django 4.0.8 on 2022-10-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
